### ISSUE TITLE
无法兼容

### ISSUE THREAD

**Issue by LeonShannon** [Chen-Xi-g/JsonToTypeScriptPlugin#2]
![image](https://github.com/Chen-Xi-g/JsonToTypeScriptPlugin/assets/24221796/7907f01b-45d5-46fa-9bd4-51adfc50cecf)

DevEco Studio NEXT Developer Beta1
Build #DS-233.14475.28.36.503403
Build Version: 5.0.3.403, built on June 20, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3928M
Cores: 16
Registry:
  idea.plugins.compatible.build=IC-233.14475.28

**Comment by Chen-Xi-g** [comment]
已适配，[点击链接](https://github.com/Chen-Xi-g/JsonToTypeScriptPlugin/releases/tag/1.0.2)到Release页面下载。
